server:
  port: 3000
  basePath: ''
application:
  domain: juice-sh.op
  name: 'SWIFT Shop'
  logo: swiftlogo.png
  favicon: swiftlogo.png
  theme: deeporange-indigo # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: true
  showGitHubLinks: true
  localBackupEnabled: true
  numberOfRandomFakeUsers: 0
  altcoinName: Juicycoin
  privacyContactEmail: donotreply@owasp-juice.shop
  customMetricsPrefix: juiceshop
  chatBot:
    name: 'Juicy'
    greeting: "Nice to meet you <customer-name>, I'm <bot-name>"
    trainingData: 'botDefaultTrainingData.json'
    defaultResponse: "Sorry I couldn't understand what you were trying to say"
    avatar: 'JuicyChatBot.png'
  social:
    twitterUrl: 'https://twitter.com/owasp_juiceshop'
    facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
    slackUrl: 'https://owasp.org/slack/invite'
    redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
    pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
    nftUrl: 'https://opensea.io/collection/juice-shop'
    questionnaireUrl: ~
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to OWASP Juice Shop!'
    message: "<p>Being a web application with a vast number of intended security vulnerabilities, the <strong>OWASP Juice Shop</strong> is supposed to be the opposite of a best practice or template application for web developers: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications. The <strong>OWASP Juice Shop</strong> is an open-source project hosted by the non-profit <a href='https://owasp.org' target='_blank'>Open Web Application Security Project (OWASP)</a> and is developed and maintained by volunteers. Check out the link below for more information and documentation on the project.</p><h1><a href='https://owasp-juice.shop' target='_blank'>https://owasp-juice.shop</a></h1>"
  cookieConsent:
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
    hiring: '/#/jobs'
  promotion:
    video: owasp_promo.mp4
    subtitles: owasp_promo.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'https://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:4200', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'https://localchromeos.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:4200', proxy: 'https://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: true
  showMitigations: true
  codingChallengesEnabled: solved # Options: never  solved  always
  restrictToTutorialsFirst: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
  showFeedbackButtons: true
hackingInstructor:
  isEnabled: true
  avatarImage: JuicyBot.png
  hintPlaybackSpeed: normal # Options: faster fast normal slow slower
products:
  -
    name: 'SWIFT Mug'
    price: 1.99
    deluxePrice: 0.99
    limitPerUser: 1
    description: 'Featuring one of our favorite co-presidents!'
    image: calpolyswiftmug.png
    reviews:
      - { text: "He's so cute!", author: jimmy }
  -
    name: 'SWIFT Hoodie'
    price: 39.99
    deluxePrice: 0.99
    description: 'Guaranteed to keep you warm'
    image: cpswifthoodie.png
  -
    name: 'SWIFT Protein'
    price: 29.99
    deluxePrice: 0.99
    description: 'The perfect supplement for getting swole'
    image: swiftprotein.png
    reviews:
      - { text: 'One of my favorites!', author: palmer }
  -
    name: 'SWIFT USB'
    price: 4.99
    deluxePrice: 0.99
    description: 'Always plug in if found on the street!'
    image: CPSWIFTUSB.png
  -
    name: 'SWIFT Fanny'
    price: 14.99
    deluxePrice: 0.99
    description: 'Stylish and portable'
    image: cpswiftfannypack.png
    reviews:
      - { text: 'Stylish and practical!', author: palmer }    
  -
    name: 'SWIFT Tote'
    price: 19.99
    deluxePrice: 0.99
    description: 'IT (Information Technology) girl energy'
    image: cpswifttote.png
    reviews:
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'SWIFT Backpack'
    price: 24.99
    deluxePrice: 0.99
    description: 'Just a backpack.'
    image: cpswiftbag.png
  -
    name: 'SWIFT Laptop Case'
    price: 12.99
    deluxePrice: 0.99
    limitPerUser: 2
    description: 'Always use protection'
    image: laptopcase.png
  -
    name: 'SWIFT Dumbbell'
    price: 12.99
    deluxePrice: 0.99
    limitPerUser: 5
    description: 'https://covertzz.github.io/markdown/2023/11/21/gym.html'
    image: calpolyswiftdumbell.png
  -
    name: 'Raspberry Juice (1000ml)'
    description: 'Made from blended Raspberry Pi, water and sugar.'
    price: 4.99
    image: raspberry_juice.jpg
  -
    name: 'OWASP SSL Advanced Forensic Tool (O-Saft)'
    description: 'O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.'
    price: 0.01
    image: orange_juice.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'Rippertuer Special Juice'
    description: 'Contains a magical collection of the rarest fruits gathered from all around the world, like Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... and others, at an unbelievable price! <br/><span style="color:red;">This item has been made unavailable because of lack of safety standards.</span>'
    price: 16.99
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'OWASP Juice Shop-CTF Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    quantity: 5
    limitPerUser: 5
    image: velcro-patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: rapper }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
  -
    name: 'Pwning OWASP Juice Shop'
    description: '<em>The official Companion Guide</em> by Bj√∂rn Kimminich available <a href="https://leanpub.com/juice-shop">for free on LeanPub</a> and also <a href="https://pwning.owasp-juice.shop">readable online</a>!'
    price: 5.99
    image: cover_small.jpg
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'OWASP Juice Shop "King of the Hill" Facemask'
    description: "Facemask with compartment for filter from 50% cotton and 50% polyester."
    price: 13.49
    quantity: 0
    limitPerUser: 1
    image: fan_facemask.jpg
    reviews:
      - { text: "K33p5 y0ur ju1cy 5plu773r 70 y0ur53lf!", author: uvogin }
      - { text: "Puny mask for puny human weaklings!", author: bender }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ-Õ°¬∞-Õú ñ-Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]-1572603645543.jpg'
    caption: 'My rare collectors item! [Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ Õ°¬∞ Õú ñ Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]'
    user: bjoernGoogle
  -
    image: 'favorite-hiking-place.png'
    caption: 'I love going hiking here...'
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: 'Daniel Boone National Forest'
  -
    image: 'IMG_4253.jpg'
    caption: 'My old workplace...'
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: 'ITsec'
  -
    image: 'BeeHaven.png'
    caption: 'Welcome to the Bee Haven (/#/bee-haven)üêù'
    user: evm
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
